name: lel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: builtin
        run: echo Branch $GITHUB_REF - Commit $GITHUB_SHA
    steps:
      - name: sh
        run: echo Commit ${{ git rev-parse --short HEAD }}
