name: lel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: builtin
        run: echo Branch $GITHUB_REF - Commit $GITHUB_SHA
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
